CREATE TABLE IF NOT EXISTS tbCustomers (coId INTEGER PRIMARY KEY, coName VARCHAR(256) NOT NULL, coStreet VARCHAR(256), coPostcode VARCHAR(256), coCity VARCHAR(256), coDistance numeric, coDescription VARCHAR(512), coDeleted INTEGER DEFAULT 0 NOT NULL);
CREATE TABLE IF NOT EXISTS tbTravelAllowance (coId INTEGER PRIMARY KEY, coRate numeric NOT NULL, coValidFrom VARCHAR(50) NOT NULL, coInvalidFrom VARCHAR(50) NOT NULL, coDeleted SMALLINT DEFAULT 0 NOT NULL);
CREATE TABLE IF NOT EXISTS tbTrip (coId INTEGER PRIMARY KEY, coTripTypeId INTEGER NOT NULL, coTimeOfTrip VARCHAR(50) NOT NULL, coCustomerId INTEGER NOT NULL, coDescription VARCHAR(512) null, coDeleted SMALLINT DEFAULT 0 NOT NULL);
CREATE TABLE IF NOT EXISTS tbTripType (coId INTEGER PRIMARY KEY, coName VARCHAR(256) NOT NULL, coDeleted SMALLINT DEFAULT 0 NOT NULL);
CREATE TABLE IF NOT EXISTS tbDatabaseHistory(coId SERIAL PRIMARY KEY, coTimestamp VARCHAR(50) NOT NULL, coDescription VARCHAR(512) NOT NULL, coBuildNumber SMALLINT DEFAULT 0 NOT NULL);
CREATE TABLE IF NOT EXISTS sqlite_sequence(name VARCHAR(256), seq INTEGER);


CREATE USER tdmuser WITH PASSWORD '<password>';
GRANT CONNECT ON DATABASE tdm TO tdmuser;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO tdmuser;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO tdmuser;
